---
title: "Propofol Main"
author: "Martin Kandlinger"
date: "2024-11-26"
output: html_document
---

Set working directory

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE, message = FALSE)
if (!require(rstudioapi)) install.packages("rstudioapi")
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
```

Initialize Analysis Environment

```{r}
# Total duration: ~10 min
# Setup tasks:
# 1. Installs/loads required packages
# 2. Creates essential data frames from already cleaned dataset (see code/preproc for more info)
# 3. Loads pre-trained models
# 4. Sources helper functions and plots from code files

start_time <- Sys.time()
cat("Initializing analysis environment...\n")

# Error handling
tryCatch(
  {
    source("source_all.R")
    cat("Setup completed successfully in", 
        round(difftime(Sys.time(), start_time, units = "mins"), 1),
        "minutes\n")
  },
  error = function(e) {
    stop("Critical setup error: ", e$message, 
         "\nPlease verify:\n",
         "1. Presence of source_all.R\n",
         "2. Package installation permissions\n"
         )
  }
)
```

Save all plots

```{r}
# Saves descriptive plots
for(i in seq_along(desc_plots)) {
  filename <- paste0("plots/descriptive/", desc_plot_names[i], ".png")
  ggsave(filename, plot = desc_plots[[i]], device = "png", width = 18, height = 8.25)
}

# Saves Forest plots
for(i in seq_along(model_plots)) {
  filename <- paste0("plots/models/", model_plot_names[i], ".png")
  ggsave(filename, plot = model_plots[[i]], device = "png", width = 18, height = 8.25)
}

# Saves plots of smooth terms
for(i in seq_along(model_splines)) {
  filename <- paste0("plots/models/", model_splines_names[i], ".png")
  ggsave(filename, plot = model_splines[[i]], device = "png", width = 18, height = 8.25)
}
```

Fit and save all models

```{r}
# Total Duration: > 12 h

# Models fit on summed data which is transformed with as_ped() from pammtools
source("code/models_data_summed.R")

# Models fit on manually created PED
source("code/models_manualPED.R")

# All Subgroup models
source("code/models_subgroups.R")
```
