---
title: "Models"
author: "Raseen Ramish"
date: "2024-11-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(data.table)
library(tidyr)
library(ggplot2)
library(dplyr)
library(patchwork)
library(wesanderson)
library("viridis")
library(survival)
library(survminer)
```

```{r}
model_data 
```

#### Datensatz in data.table format:

```{r}
model_data.tbl <- copy(as.data.table(model_data))
patient.tbl <- copy(as.data.table(patient))
ICU.tbl <- copy(as.data.table(ICU))
```


#### wie survival variable für Frauen und Männer vertilt ist: 
IDEE: Weibull distrubution,

```{r}
model_data.tbl[!is.na(Surv0to60), .(Surv0to60)] %>% ggplot(aes(Surv0to60))  + theme_bw() + geom_histogram(aes(y = ..density..), fill = "lightblue", colour = 1)+ geom_density(color = "red", lwd = 1.2, linetype = 2)
```


#### Kaplen Meier Analysis :
! die Datensatz ist nict korrekt

```{r}
attach(model_data)
KmModel <- survfit(Surv(Surv0to60, PatientDied)~ Sex)
KmModel
ggsurvplot(KmModel, data = model_data.tbl, risk.table = TRUE, ggtheme = theme_bw())
```


#### cox Proportional Hazard Model:
! die Datensatz ist nict korrekt

```{r}
attach(model_data)
coxMod <- coxph(Surv(Surv0to60, PatientDied) ~ Age + BMI + ApacheIIScore + totalPropofolCal)
summary(coxMod )
```

